// <auto-generated />
using System;
using LMSWebAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LMSWebAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LMSWebAPI.Models.Lead", b =>
                {
                    b.Property<int>("lead_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("lead_id"));

                    b.Property<int>("assigned_to")
                        .HasColumnType("int");

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("lead_contact")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("lead_email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("lead_name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("lead_source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("lead_status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("New");

                    b.Property<DateTime?>("update_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("lead_id");

                    b.HasIndex("assigned_to");

                    b.ToTable("leads", (string)null);
                });

            modelBuilder.Entity("LMSWebAPI.Models.LeadAssignment", b =>
                {
                    b.Property<int>("assignment_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("assignment_id"));

                    b.Property<DateTime>("assignment_date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("lead_id")
                        .HasColumnType("int");

                    b.Property<int>("u_id")
                        .HasColumnType("int");

                    b.HasKey("assignment_id");

                    b.HasIndex("lead_id");

                    b.HasIndex("u_id");

                    b.ToTable("lead_assignment", (string)null);
                });

            modelBuilder.Entity("LMSWebAPI.Models.LeadLog", b =>
                {
                    b.Property<int>("status_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("status_id"));

                    b.Property<int>("lead_id")
                        .HasColumnType("int");

                    b.Property<string>("new_status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("old_status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("update_by")
                        .HasColumnType("int");

                    b.Property<DateTime?>("update_date")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("status_id");

                    b.HasIndex("lead_id");

                    b.HasIndex("update_by");

                    b.ToTable("lead_log", (string)null);
                });

            modelBuilder.Entity("LMSWebAPI.Models.User", b =>
                {
                    b.Property<int>("u_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("u_id"));

                    b.Property<string>("contact_no")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("role")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("u_email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("u_name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("u_password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("u_id");

                    b.HasIndex("u_email")
                        .IsUnique();

                    b.HasIndex("u_name")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Lms.Models.ActivityLog", b =>
                {
                    b.Property<int>("activity_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("activity_id"));

                    b.Property<DateTime>("action_date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("action_type")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("lead_id")
                        .HasColumnType("int");

                    b.Property<int>("u_id")
                        .HasColumnType("int");

                    b.HasKey("activity_id");

                    b.HasIndex("action_date");

                    b.HasIndex("lead_id");

                    b.HasIndex("u_id");

                    b.ToTable("activity_log", (string)null);
                });

            modelBuilder.Entity("LMSWebAPI.Models.Lead", b =>
                {
                    b.HasOne("LMSWebAPI.Models.User", null)
                        .WithMany()
                        .HasForeignKey("assigned_to")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_leads_users_assigned_to");
                });

            modelBuilder.Entity("LMSWebAPI.Models.LeadAssignment", b =>
                {
                    b.HasOne("LMSWebAPI.Models.Lead", null)
                        .WithMany()
                        .HasForeignKey("lead_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_lead_assignment_leads");

                    b.HasOne("LMSWebAPI.Models.User", null)
                        .WithMany()
                        .HasForeignKey("u_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_lead_assignment_users");
                });

            modelBuilder.Entity("LMSWebAPI.Models.LeadLog", b =>
                {
                    b.HasOne("LMSWebAPI.Models.Lead", null)
                        .WithMany()
                        .HasForeignKey("lead_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_lead_log_leads");

                    b.HasOne("LMSWebAPI.Models.User", null)
                        .WithMany()
                        .HasForeignKey("update_by")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_lead_log_users");
                });

            modelBuilder.Entity("Lms.Models.ActivityLog", b =>
                {
                    b.HasOne("LMSWebAPI.Models.Lead", null)
                        .WithMany()
                        .HasForeignKey("lead_id")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_activity_log_leads");

                    b.HasOne("LMSWebAPI.Models.User", null)
                        .WithMany()
                        .HasForeignKey("u_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_activity_log_users");
                });
#pragma warning restore 612, 618
        }
    }
}
